servo_node:
  ros__parameters:
    moveit_servo:
      move_group_name: fr3_arm
      
      planning_frame: base
      robot_link_command_frame: base
      ee_frame_name: fr3_hand_tcp

      cartesian_command_in_topic: /delta_twist_cmds
      joint_command_in_topic: /delta_joint_cmds
      status_topic: /status
      
      linear_scale: 0.4
      rotational_scale: 0.8
      
      publish_period: 0.01
      incoming_command_timeout: 0.5
      
      command_out_type: trajectory_msgs/JointTrajectory
      command_out_topic: /fr3_arm_controller/joint_trajectory
      
      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false
      
      is_primary_joint_state_publisher: true

